stock:
  build: stock/
  entrypoint: go run /go/src/github.com/ryuzaki01/go-ms/stock/main.go
  ports:
    - "3000:80"
  environment:
    - APP_SECRET
  container_name: 'stock'

encrypt:
  build: encrypt/
  entrypoint: go run /go/src/github.com/ryuzaki01/go-ms/encrypt/main.gos
  ports:
    - "3001:80"
  environment:
    - APP_SECRET
  container_name: 'encrypt'