networks:
  isolation-network:
    driver: bridge

services:
  stock:
    build: stock/
    entrypoint: go run /go/src/github.com/ryuzaki01/go-ms/stock/main.go
    ports:
      - "3000:3000"
    environment:
      - APP_SECRET
    container_name: 'stock'
    networks:
      - isolation-network

  encrypt:
    build: encrypt/
    entrypoint: go run /go/src/github.com/ryuzaki01/go-ms/encrypt/main.go
    ports:
      - "3001:3001"
    environment:
      - APP_SECRET
    container_name: 'encrypt'
    networks:
      - isolation-network